import { FC } from 'react';
import { motion } from 'framer-motion';
import Image from 'next/image';

interface AboutProps {
  isDarkMode: boolean;
}

const About: FC<AboutProps> = ({ isDarkMode }) => {
  return (
    <section id="about" className="relative flex items-center py-8">
      <motion.div 
        className="relative w-full max-w-7xl mx-auto px-4 py-8"
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true }}
        transition={{ duration: 0.8 }}
      >
        <h2 className="text-5xl font-bold text-center text-transparent bg-clip-text 
          bg-gradient-to-r from-blue-500 to-purple-500 mb-16">
          About the Paper
        </h2>
        
        <div className="flex justify-center mb-12">
          <div className={`${isDarkMode ? 'bg-[#0f1729]/80' : 'bg-white/90'} backdrop-blur-sm p-8 rounded-xl border ${isDarkMode ? 'border-blue-500/20' : 'border-slate-200'} shadow-lg`}>
            <Image
              src="/overview/paper_overview.jpg"
              alt="Code TREAT Paper Overview"
              width={1200}
              height={800}
              className="rounded-lg max-w-full h-auto"
              priority
            />
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          <div className={`${isDarkMode ? 'bg-[#0f1729]/80' : 'bg-white/90'} backdrop-blur-sm p-8 rounded-xl border ${isDarkMode ? 'border-blue-500/20' : 'border-slate-200'} shadow-sm`}>
            <h3 className="text-3xl font-semibold mb-6 text-transparent bg-clip-text bg-gradient-to-r from-blue-500 to-purple-500">
              Abstract
            </h3>
            <p className={`text-lg leading-relaxed ${isDarkMode ? 'text-blue-200' : 'text-slate-600'}`}>
              Code TREAT provides a comprehensive evaluation framework for assessing the trustworthiness, 
              reliability, effectiveness, and applicability of code generated by Large Language Models (LLMs). 
              Our benchmark covers multiple programming tasks, languages, and evaluation metrics to provide 
              a holistic view of LLM capabilities in code generation.
            </p>
          </div>
          
          <div className={`${isDarkMode ? 'bg-[#0f1729]/80' : 'bg-white/90'} backdrop-blur-sm p-8 rounded-xl border ${isDarkMode ? 'border-blue-500/20' : 'border-slate-200'} shadow-sm`}>
            <h3 className="text-3xl font-semibold mb-6 text-transparent bg-clip-text bg-gradient-to-r from-blue-500 to-purple-500">
              Contact Information
            </h3>
            <div className="space-y-4">
              <div>
                <p className={`text-lg ${isDarkMode ? 'text-blue-200' : 'text-slate-600'} mb-2`}>
                  For questions about this research, please contact:
                </p>
                <a 
                  href="mailto:lyu@cse.cuhk.edu.hk,ejli@cse.cuhk.edu.hk"
                  className={`text-lg text-transparent bg-clip-text bg-gradient-to-r from-blue-500 to-purple-500 hover:underline`}
                >
                  lyu@cse.cuhk.edu.hk, ejli@cse.cuhk.edu.hk
                </a>
              </div>
            </div>
          </div>
        </div>
      </motion.div>
    </section>
  );
};

export default About;
