import { FC } from 'react';
import { motion } from 'framer-motion';

interface AboutProps {
  isDarkMode: boolean;
  onNavigateToTask?: (task: string) => void;
}

const About: FC<AboutProps> = ({ isDarkMode, onNavigateToTask }) => {
  return (
    <section id="about" className="relative flex items-center py-8">
      <motion.div 
        className="relative w-full max-w-7xl mx-auto px-4 py-8"
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true }}
        transition={{ duration: 0.8 }}
      >
        <h2 className="text-5xl font-bold text-center text-transparent bg-clip-text 
          bg-gradient-to-r from-blue-500 to-purple-500 mb-24">
          About Code TREAT
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-24">
          <div className={`${isDarkMode ? 'bg-[#0f1729]/80' : 'bg-white/90'} backdrop-blur-sm p-6 rounded-xl text-center border ${isDarkMode ? 'border-blue-500/20' : 'border-slate-200'} shadow-sm`}>
            <h3 className="text-2xl font-semibold mb-3 text-transparent bg-clip-text bg-gradient-to-r from-blue-500 to-purple-500">
              Trustworthiness Analysis
            </h3>
            <p className={`text-xl ${isDarkMode ? 'text-blue-200' : 'text-slate-600'}`}>
              Evaluate the reliability of code generated by Large Language Models
            </p>
          </div>
          <div className={`${isDarkMode ? 'bg-[#0f1729]/80' : 'bg-white/90'} backdrop-blur-sm p-6 rounded-xl text-center border ${isDarkMode ? 'border-blue-500/20' : 'border-slate-200'} shadow-sm`}>
            <h3 className="text-2xl font-semibold mb-3 text-transparent bg-clip-text bg-gradient-to-r from-blue-500 to-purple-500">
              Reliability Testing
            </h3>
            <p className={`text-xl ${isDarkMode ? 'text-blue-200' : 'text-slate-600'}`}>
              Comprehensive testing framework for AI-generated code
            </p>
          </div>
          <div className={`${isDarkMode ? 'bg-[#0f1729]/80' : 'bg-white/90'} backdrop-blur-sm p-6 rounded-xl text-center border ${isDarkMode ? 'border-blue-500/20' : 'border-slate-200'} shadow-sm`}>
            <h3 className="text-2xl font-semibold mb-3 text-transparent bg-clip-text bg-gradient-to-r from-blue-500 to-purple-500">
              Performance Metrics
            </h3>
            <p className={`text-xl ${isDarkMode ? 'text-blue-200' : 'text-slate-600'}`}>
              Detailed analysis of code quality and performance
            </p>
          </div>
        </div>
      </motion.div>
    </section>
  );
};

export default About; 